### PR TITLE
Enable HSTS in Frontend pod and Support for AL_HSTS_MAX_AGE environment variable 

### PR DESCRIPTION
**Pull request by microblag**
Support for AL_HSTS_MAX_AGE environment variable in ui pod.

Add serve.json when enabled to set the HSTS header in the frontend pod.

See PR https://github.com/CybercentreCanada/assemblyline-ui/pull/818 for further details.

### CODE REVIEW

**Review by cccs-sgaron — CHANGES_REQUESTED** [review]
The enableHSTSHeader and HSTSMaxAge variable should have a default value with enableHSTSHeader set to false in the values.yml.

But first refer to my question about this patch in the UI PR:
https://github.com/CybercentreCanada/assemblyline-ui/pull/818#issuecomment-1943820597

**Comment by cccs-sgaron** [comment]
The UI API related to this was approved, please set default values in the helm chart.

**Review by cccs-sgaron — APPROVED** [review]

**Review by cccs-rs — APPROVED** [review]

**Review by cccs-rs — CHANGES_REQUESTED** [review]
`HSTSMaxAge` will have to be a string as it seems Helm doesn't set the value as expected within the API containers which leads to a crash when Python tries to cast that value as an integer:
image

Resolutions
`HSTSMaxAge: "31536000"`

**Comment by cccs-rs** [comment]
Closing in favour of: https://github.com/CybercentreCanada/assemblyline-helm-chart/pull/109

**Pull request closed without merging**
